Repository alphagov/govuk-design-system, pull requests merged in 2021-08, with the labels that each got.

#1789 Update guidance on radios
  src/components/radios/index.md.njk
Labels: contribution, guidance, 🕔 days

#1807 Corrected phone number
  src/patterns/telephone-numbers/index.md.njk
Labels: documentation

#1808 Add guidance on when to ignore whitespace in form inputs
  src/patterns/validation/index.md.njk
Labels: guidance, validation errors

#1811 Add MIT license and GitHub info to Components page
  src/components/index.md.njk
Labels: documentation, 2i, small story

#1817 Remove graph mentions from Colour guidance
  src/styles/colour/index.md.njk
Labels: 🕔 hours, colour, guidance, small story

#1830 Write out accordion guidance numbers in full
  src/components/accordion/index.md.njk
Labels: 🕔 hours, accordion, guidance, small story

#1829 Replace negative contractions in Patterns guidance
  src/patterns/addresses/index.md.njk
  src/patterns/equality-information/explainer-screen/index.njk
  src/patterns/question-pages/index.md.njk
Labels: accessibility, guidance

#1835 Add width layout advice to Check answers guidance
  src/patterns/check-answers/index.md.njk
  src/styles/layout/index.md.njk
Labels: 🕔 hours, design, guidance, small story

#1836 Link Colour guidance to Frontend Sass docs
  src/styles/colour/index.md.njk
Labels: documentation, 🕔 hours, guidance, small story

#1846 Fix incorrect link
  src/patterns/cookies-page/index.md.njk
Labels: 🐛 bug, documentation, 🕔 hours, small story
