Repository alphagov/govuk-design-system, pull requests merged in 2021-06, with the labels that each got.

#1694 Add content about using step-by-step only on GOVUK
  src/patterns/step-by-step-navigation/index.md.njk
Labels: guidance, 🕔 hours

#1713 Clarify when a service needs a phase banner
  src/components/phase-banner/index.md.njk
Labels: phase banner

#1712 Add `cspNonce` option to Page template guidance
  src/styles/page-template/index.md.njk
Labels: guidance
