Repository alphagov/govuk-design-system, pull requests merged in 2021-05, with the labels that each got.

#1662 Fix URL in link to sass-lint
  README.md
Labels: documentation, 🕔 hours

#1655 Add mobile tabs issue to Accessibility Statement
  src/accessibility.md.njk
Labels: accessibility, documentation, 🕔 hours

#1673 Make Equality Info example question accessible
  src/patterns/equality-information/sexual-orientation/index.njk
Labels: guidance

#1674 Add correct usage to hint text guidance
  src/components/text-input/index.md.njk
Labels: documentation, guidance, 🕔 hours
