Repository alphagov/govuk-design-system, pull requests merged in 2022-10, with the labels that each got.

#2354 Update backlog page
  .github/ISSUE_TEMPLATE/feature-request.md
  src/community/backlog/index.md.njk
  src/community/contribution-criteria/index.md.njk
  src/community/index.md.njk
  src/community/upcoming-components-patterns/index.md.njk
  src/get-started/extending-and-modifying-components/index.md.njk
  src/index.njk
Labels: community, contribution, Design System squad

#2392 Tidy up references to the community backlog
  src/community/backlog.md.njk
  src/community/contribution-criteria/index.md.njk
  src/community/develop-a-component-or-pattern/index.md.njk
  src/community/index.md.njk
  src/community/propose-a-component-or-pattern/index.md.njk
  src/get-started/extending-and-modifying-components/index.md.njk
  src/get-started/focus-states/index.md.njk
  src/index.njk
Labels: guidance, consistency, Design System squad

#2400 Add blog post on MOJ bank details contribution
  src/community/blogs-talks-podcasts/index.md.njk
Labels: shared ownership

#2399 Allow Node.js LTS ‘Gallium’ (v16) release version
  .nvmrc
  bin/check-nvmrc.js
  package-lock.json
  package.json
Labels: tooling, Frontend squad
