Repository alphagov/govuk-design-system, pull requests merged in 2022-11, with the labels that each got.

#2404 Update all dependencies using Dependabot
  .github/dependabot.yml
Labels: 🕔 hours, dependencies, tooling, Frontend squad

#2436 Replace metalsmith-assets with metalsmith-include-files
  lib/metalsmith.js
  package-lock.json
  package.json
Labels: tooling

#2427 Update Marked and switch to Github Flavoured Markdown
  lib/file-helper.js
  lib/metalsmith.js
  package-lock.json
  package.json
  src/accessibility.md.njk
  src/community/contribution-criteria/index.md.njk
  src/community/develop-a-component-or-pattern/index.md.njk
  src/community/propose-a-content-change-using-github/index.md.njk
  src/community/roadmap/index.md.njk
  src/components/accordion/index.md.njk
  src/components/cookie-banner/index.md.njk
  src/components/footer/index.md.njk
  src/components/notification-banner/index.md.njk
  src/components/pagination/index.md.njk
  src/components/radios/index.md.njk
  src/components/tabs/index.md.njk
  src/get-started/extending-and-modifying-components/index.md.njk
  src/get-started/updating-your-code/index.md.njk
  src/patterns/confirm-a-phone-number/index.md.njk
  src/patterns/cookies-page/index.md.njk
  src/patterns/dates/index.md.njk
  src/patterns/question-pages/index.md.njk
  src/patterns/start-using-a-service/index.md.njk
  src/privacy-policy.md.njk
  src/styles/colour/index.md.njk
  src/styles/page-template/index.md.njk
  src/styles/typography/index.md.njk
  views/partials/_example.njk
Labels: tooling, Frontend squad
