Repository alphagov/govuk-design-system, pull requests merged in 2022-08, with the labels that each got.

#2276 Replace metalsmith-tagcleaner with a custom marked renderer
  lib/marked-renderer.js
  lib/metalsmith.js
  package-lock.json
  package.json
Labels: tooling, tech debt, javascript squad

#2303 Update govuk-frontend to 4.3.0
  package-lock.json
  package.json
Labels: 🚀 release

#2291 Add alias for section break
  lib/extract-page-headings/fixtures/src/example-with-aliases.md.njk
  lib/extract-page-headings/index.js
  lib/extract-page-headings/index.test.js
  lib/metalsmith-lunr-index/fixtures/src/with-page-headings.md.njk
  lib/metalsmith-lunr-index/index.js
  lib/metalsmith-lunr-index/index.test.js
  src/styles/typography/index.md.njk
Labels: website

#2314 Add ‘Measuring the value of the GOV.UK Design System’ talk to the blog posts, videos and podcasts page
  src/community/blogs-talks-podcasts/index.md.njk
Labels: contribution squad
