Repository alphagov/govuk-design-system, pull requests merged in 2022-06, with the labels that each got.

#2210 Add Claire to team page
  src/design-system-team.md.njk
Labels: contribution squad

#2212 Remove last line about performance platform
  src/patterns/payment-card-details/index.md.njk
Labels: documentation

#1972 Guidance for pagination component
  src/community/roadmap/index.md.njk
  src/components/pagination/default/index.njk
  src/components/pagination/ellipses/index.njk
  src/components/pagination/first-page/index.njk
  src/components/pagination/in-page/index.njk
  src/components/pagination/index.md.njk
  src/components/pagination/labels-2/index.njk
  src/components/pagination/labels/index.njk
  src/components/pagination/large-number-of-pages/index.njk
  src/components/pagination/last-page/index.njk
Labels: guidance, contribution, contribution squad
