Repository alphagov/govuk-design-system, pull requests merged in 2022-12, with the labels that each got.

#2445 Adding the accessibility strategy
  src/community/accessibility-strategy/index.md.njk
Labels: Design System squad

#2478 Remove reference to GOV.UK Pay's direct debit
  src/patterns/bank-details/index.md.njk
Labels: payment card details, guidance

#2491 Replace metalsmith-tagcleaner with custom Marked renderer
  lib/marked-renderer.js
  lib/metalsmith.js
  package-lock.json
  package.json
Labels: dependencies, tooling, tech debt

#2506 Configure Dependabot for direct updates only
  .github/dependabot.yml
  package-lock.json
Labels: dependencies, tooling, Frontend squad

#2503 Replace metalsmith-browser-sync with our own plugin
  lib/metalsmith-browser-sync.js
  package-lock.json
  package.json
  tasks/serve.js
Labels: dependencies, tooling

#2509 [Fix] Update package-lock
  package-lock.json
Labels: dependencies

#2477 Update homepage links to recent updates
  src/index.njk
  views/partials/_footer.njk
Labels: guidance, Design System squad
