Repository alphagov/govuk-design-system, pull requests merged in 2023-01, with the labels that each got.

#2516 Adds links to Figma file for GOVUK Flow Diagrams
  src/community/resources-and-tools/index.md.njk
Labels: documentation

#2532 Upgrade browser/accessibility tests for Puppeteer v18
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/test.yaml
  __tests__/accessiblity-audit.test.js
  __tests__/back-to-top.test.js
  __tests__/component-options.test.js
  __tests__/cookie-banner.test.js
  __tests__/cookies-page.test.js
  __tests__/example.test.js
  __tests__/navigation.test.js
  __tests__/search.test.js
  __tests__/tabs.test.js
  config/jest/.eslintrc.js
  config/jest/matchers.js
  jest-puppeteer.config.js
  jest.config.mjs
  jest.setup.js
  lib/jest-utilities.js
  lib/puppeteer-helpers.js
  package-lock.json
  package.json
Labels: accessibility, tech debt, Frontend squad

#2540 Write to `sitemap.xml` + `modernizr.js` using metalsmith
  lib/generate-sitemap.js
  lib/metalsmith.js
  lib/modernizr-build.js
  src/styles/page-template/block-areas/index.njk
  src/styles/page-template/custom/index.njk
  src/styles/page-template/default/index.njk
  views/layouts/_generic.njk
  views/layouts/layout-example-full-page-govuk.njk
  views/layouts/layout-example-full-page.njk
  views/layouts/layout-example.njk
Labels: tech debt, Frontend squad

#2541 Prevent duplicate checks on GitHub Actions "Test" workflow
  .github/workflows/test.yaml
Labels: 🐛 bug, Frontend squad

#2539 Use standalone Terser minifier via Rollup task
  jest.config.mjs
  lib/metalsmith.js
  lib/rollup/fixtures/.gitignore
  lib/rollup/fixtures/src/javascripts/entry.js
  lib/rollup/fixtures/src/javascripts/example.js
  lib/rollup/index.js
  lib/rollup/index.test.js
  package-lock.json
  package.json
  package.json.unit.test.js
Labels: javascript, tech debt, Frontend squad

#2497 Add source maps to compiled JavaScript and CSS
  lib/file-helper.js
  lib/fingerprints/fixtures/.eslintrc.js
  lib/fingerprints/fixtures/.gitignore
  lib/fingerprints/fixtures/src/example-source-map.css
  lib/fingerprints/fixtures/src/example-source-map.css.map
  lib/fingerprints/fixtures/src/example-source-map.js
  lib/fingerprints/fixtures/src/example-source-map.js.map
  lib/fingerprints/fixtures/src/example.jpg
  lib/fingerprints/fixtures/src/example.js
  lib/fingerprints/fixtures/src/example.json
  lib/fingerprints/index.js
  lib/fingerprints/index.test.js
  lib/metalsmith.js
  lib/rollup/index.js
  lib/rollup/index.test.js
  package-lock.json
  package.json
  views/partials/_header.njk
Labels: javascript, sass / css, tech debt

#2556 Fix issue with Rollup `config.input` in watch mode
  lib/rollup/index.js
Labels: 🐛 bug

#2251 Summary card
  src/components/summary-list/card-with-actions/index.njk
  src/components/summary-list/card-with-title/index.njk
  src/components/summary-list/index.md
  src/patterns/check-answers/index.md
Labels: summary list, contribution

#2557 Update roadmap for v4.5.0 release
  src/community/roadmap/index.md
Labels: 🚀 release

#2573 Add missing `[hidden]` styling on tabs for IE8-10 compatibility
  src/stylesheets/components/_tabs.scss
Labels: 🐛 bug, Frontend squad

#2565 Render all Nunjucks before Markdown runs
  lib/metalsmith-lunr-index/fixtures/src/about-larry.md
  lib/metalsmith-lunr-index/fixtures/src/checkboxes.md
  lib/metalsmith-lunr-index/fixtures/src/dates.md
  lib/metalsmith-lunr-index/fixtures/src/example.md
  lib/metalsmith-lunr-index/fixtures/src/radios.md
  lib/metalsmith-lunr-index/fixtures/src/with-permalink.md
  lib/metalsmith-lunr-index/index.test.js
  lib/metalsmith.js
  package-lock.json
  package.json
Labels: 🐛 bug, Frontend squad
