Repository alphagov/govuk-design-system, pull requests merged in 2023-07, with the labels that each got.

#2721 Add guidance for Exit this page component and pattern
  src/components/exit-this-page/default/index.njk
  src/components/exit-this-page/index.md
  src/components/exit-this-page/secondary-link/index.njk
  src/patterns/exit-a-page-quickly/index.md
  src/patterns/exit-a-page-quickly/safety-content-example/index.njk
Labels: guidance

#2933 Add navigation sub items using Metalsmith `files`
  lib/file-helper.js
  lib/metalsmith.js
  lib/navigation.js
Labels: submitted by user, tooling

#2942 Metalsmith build, environment, metadata improvements
  .github/workflows/test.yaml
  lib/debug.js
  lib/extract-page-headings/index.test.js
  lib/fingerprints/index.test.js
  lib/metalsmith-browser-sync.js
  lib/metalsmith-lunr-index/index.test.js
  lib/metalsmith.js
  lib/rollup/index.test.js
  package-lock.json
  package.json
  views/layouts/_generic.njk
Labels: tooling, website

#2943 Use exact GitHub Actions versions
  .github/workflows/deploy.yaml
  .github/workflows/test.yaml
Labels: github_actions

#2941 Initialise iFrame resizing as each iFrame loads
  __tests__/accessibility-audit.test.js
  src/components/accordion/index.md
  src/components/back-link/index.md
  src/components/breadcrumbs/index.md
  src/components/button/index.md
  src/components/character-count/index.md
  src/components/checkboxes/index.md
  src/components/cookie-banner/index.md
  src/components/date-input/index.md
  src/components/details/index.md
  src/components/error-message/index.md
  src/components/error-summary/index.md
  src/components/exit-this-page/index.md
  src/components/fieldset/index.md
  src/components/file-upload/index.md
  src/components/footer/index.md
  src/components/header/index.md
  src/components/inset-text/index.md
  src/components/notification-banner/index.md
  src/components/pagination/index.md
  src/components/panel/index.md
  src/components/phase-banner/index.md
  src/components/radios/index.md
  src/components/select/index.md
  src/components/skip-link/index.md
  src/components/summary-list/index.md
  src/components/table/index.md
  src/components/tabs/index.md
  src/components/tag/index.md
  src/components/text-input/index.md
  src/components/textarea/index.md
  src/components/warning-text/index.md
  src/get-started/labels-legends-headings/index.md
  src/get-started/prototyping/index.md
  src/javascripts/components/example.mjs
  src/patterns/addresses/index.md
  src/patterns/bank-details/index.md
  src/patterns/check-answers/index.md
  src/patterns/confirm-a-phone-number/index.md
  src/patterns/confirmation-pages/index.md
  src/patterns/dates/index.md
  src/patterns/email-addresses/index.md
  src/patterns/equality-information/index.md
  src/patterns/names/index.md
  src/patterns/national-insurance-numbers/index.md
  src/patterns/page-not-found-pages/index.md
  src/patterns/problem-with-the-service-pages/index.md
  src/patterns/question-pages/index.md
  src/patterns/service-unavailable-pages/index.md
  src/patterns/telephone-numbers/index.md
  src/styles/layout/index.md
  src/styles/page-template/index.md
  src/styles/typography/index.md
  views/partials/_example.njk
Labels: 🐛 bug, examples, website

#2979 Fix preview banner
  lib/metalsmith.js
  views/partials/_banner.njk
Labels: 🐛 bug
