Repository alphagov/govuk-design-system, pull requests merged in 2023-02, with the labels that each got.

#2581 Prevent Browsersync full page reloads on `*.map` changes
  lib/metalsmith-browser-sync.js
Labels: 🐛 bug, Frontend squad

#2585 Ensure mismatched source map URLs are still hashed
  lib/fingerprints/fixtures/src/example-xxx-123.js
  lib/fingerprints/fixtures/src/example-xxx-456.map
  lib/fingerprints/index.js
  lib/fingerprints/index.test.js
Labels: 🐛 bug

#2572 Pin to `iframe-resizer@3.5.15` for IE8-10 compatibility
  .github/dependabot.yml
  __tests__/tabs.test.js
  lib/metalsmith.js
  package-lock.json
  package.json
  src/javascripts/components/example.js
  src/styles/page-template/block-areas/index.njk
  src/styles/page-template/custom/index.njk
  src/styles/page-template/default/index.njk
  views/layouts/_generic.njk
  views/layouts/layout-example-full-page-govuk.njk
  views/layouts/layout-example-full-page.njk
  views/layouts/layout-example.njk
Labels: 🐛 bug

#2584 Ask users to tell us when they've made a proposal
  src/community/propose-a-component-or-pattern/index.md
Labels: small story

#2552 Replace the DfE Rails boilerplate with the new Rails template
  src/community/resources-and-tools/index.md
Labels: 🕔 days, contribution

#2586 Clarify error message in Checkboxes component
  src/components/checkboxes/index.md
Labels: small story

#2531 Add GOV.UK Frontend Flask community resource
  src/community/resources-and-tools/index.md
Labels: community, contribution

#2578 Use Markdown to render all code blocks
  lib/file-helper.js
  lib/marked-renderer.js
  lib/metalsmith.js
  src/get-started/focus-states/index.md
  src/get-started/updating-your-code/index.md
  views/partials/_example.njk
Labels: 🐛 bug, sass / css

#2562 Fix various code highlighting issues
  lib/file-helper.js
  lib/highlighter.js
Labels: 🐛 bug, sass / css

#2563 Enable text wrapping in markdown/plaintext code
  src/stylesheets/main.scss
Labels: Enhancement: feature-request, sass / css

#2569 Lint compiled HTML
  .github/workflows/test.yaml
  .htmlvalidate.js
  .htmlvalidateignore
  package-lock.json
  package.json
  src/community/index.md
  src/components/footer/index.md
  src/cookies.njk
  src/get-started/labels-legends-headings/legend-m-s/index.njk
  src/patterns/confirm-a-phone-number/index.md
  src/patterns/service-unavailable-pages/available-at-known-date/index.njk
  src/patterns/service-unavailable-pages/default/index.njk
  src/styles/colour/index.md
  src/styles/page-template/index.md
  views/layouts/_generic.njk
  views/layouts/layout-example-full-page-govuk.njk
  views/layouts/layout-example-full-page.njk
  views/layouts/layout-example.njk
  views/partials/_example.njk
  views/partials/_image-card.njk
  views/partials/_navigation.njk
Labels: tooling

#2645 Fix broken anchor links
  .github/workflows/test.yaml
  lib/metalsmith.js
  package-lock.json
  package.json
  src/community/blogs-talks-podcasts/index.md
  src/components/error-summary/default/index.njk
  src/components/footer/with-meta/index.njk
  src/components/footer/with-navigation/index.njk
  src/components/header/with-service-name-and-navigation/index.njk
  src/components/skip-link/default/index.njk
  src/get-started/extending-and-modifying-components/index.md
  src/get-started/updating-your-code/index.md
  src/styles/page-template/custom/code.njk
  src/styles/page-template/custom/index.njk
Labels: 🐛 bug, findability
