Repository alphagov/govuk-design-system, pull requests merged in 2023-11, with the labels that each got.

#3270 Allow Node.js LTS ‘Iron’ (v20) release version
  .browserslistrc
  .github/workflows/test.yaml
  .nvmrc
  package-lock.json
  package.json
Labels: tooling, github_actions

#3291 New guidance on matching error message text to input label
  src/components/error-message/index.md
  src/patterns/addresses/error-messages/index.njk
Labels: accessibility, guidance, audit may 2023

#3307 Prevent search engine indexing for Netlify branch deployments
  lib/metalsmith.js
  views/layouts/_generic.njk
Labels: 🐛 bug
