Repository alphagov/govuk-design-system, pull requests merged in 2023-08, with the labels that each got.

#2996 Add usability issue to file upload component
  src/components/file-upload/index.md
Labels: accessibility, website

#2861 Add guidance on show/hide password buttons
  src/patterns/passwords/index.md
Labels: accessibility, guidance

#3026 Step-by-step to meet WCAG 2.1
  src/patterns/step-by-step-navigation/index.md
Labels: accessibility, guidance

#3039 Fix typo affecting default iframe height
  src/stylesheets/components/_example.scss
Labels: 🐛 bug, examples, website

#3038 Fix Puppteeer tab link double click issue
  __tests__/tabs.test.js
Labels: 🐛 bug, assurance

#3030 Tabs to meet WCAG 2.1
  src/components/tabs/index.md
Labels: accessibility, tabs

#2889 Update date input to recommend accepting month names
  src/components/date-input/index.md
Labels: submitted by user, date input, guidance

#3000 Format Sass stylesheets using Prettier
  .prettierrc.js
  .stylelintrc.yml
  package-lock.json
  package.json
  src/styles/page-template/block-areas/block-areas-annotate.scss
  src/stylesheets/components/_back-to-top.scss
  src/stylesheets/components/_example.scss
  src/stylesheets/components/_navigation.scss
  src/stylesheets/components/_page-navigation.scss
  src/stylesheets/components/_site-search.scss
  src/stylesheets/components/_subnav.scss
  src/stylesheets/components/_tabs.scss
  src/stylesheets/main.scss
  stylelint.config.js
Labels: sass / css, assurance, tooling

#3070 Enable `continue-on-error` for Prettier check
  .github/workflows/test.yaml
Labels: github_actions

#3057 Format JavaScript using Prettier
  .eslintrc.js
  __tests__/accessibility-audit.test.js
  __tests__/back-to-top.test.js
  __tests__/component-options.test.js
  __tests__/cookie-banner.test.js
  __tests__/cookie-functions.test.mjs
  __tests__/cookies-page.test.js
  __tests__/navigation.test.js
  __tests__/search.test.js
  __tests__/tabs.test.js
  babel.config.js
  jest-puppeteer.config.js
  lib/colours.js
  lib/extract-page-headings/index.js
  lib/extract-page-headings/index.test.js
  lib/file-helper.js
  lib/fingerprints/index.js
  lib/fingerprints/index.test.js
  lib/generate-sitemap.js
  lib/get-macro-options/__mocks__/fs.js
  lib/get-macro-options/__tests__/index.js
  lib/get-macro-options/index.js
  lib/highlighter.js
  lib/marked-renderer.js
  lib/metalsmith-lunr-index/index.js
  lib/metalsmith-lunr-index/index.test.js
  lib/metalsmith-title-checker.js
  lib/metalsmith.js
  lib/navigation.js
  lib/puppeteer-helpers.js
  lib/rollup/index.js
  lib/rollup/index.test.js
  package-lock.json
  package.json
  rollup.config.js
  src/.eslintrc.js
  src/javascripts/application.mjs
  src/javascripts/components/analytics.mjs
  src/javascripts/components/back-to-top.mjs
  src/javascripts/components/cookie-banner.mjs
  src/javascripts/components/cookie-functions.mjs
  src/javascripts/components/cookies-page.mjs
  src/javascripts/components/copy.mjs
  src/javascripts/components/example.mjs
  src/javascripts/components/helpers.mjs
  src/javascripts/components/navigation.mjs
  src/javascripts/components/options-table.mjs
  src/javascripts/components/search.mjs
  src/javascripts/components/search.tracking.mjs
  src/javascripts/components/tabs.mjs
  src/javascripts/example.mjs
  tasks/build.js
Labels: javascript, assurance, tooling

#2927 Allow macro options to wrap at full stops and capital letters
  lib/get-macro-options/index.js
  lib/metalsmith.js
  src/stylesheets/components/_options.scss
  views/partials/_example.njk
Labels: documentation, design, website

#2999 Enable ESLint + Stylelint for code inside Markdown
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/internal-story.md
  README.md
  docs/contributing/archiving-deleted-urls.md
  lib/colours.js
  lib/get-macro-options/index.js
  lib/highlighter.js
  package-lock.json
  package.json
  src/community/index.md
  src/get-started/extending-and-modifying-components/index.md
  src/get-started/updating-your-code/index.md
  src/patterns/page-not-found-pages/index.md
  src/patterns/problem-with-the-service-pages/index.md
  src/patterns/service-unavailable-pages/index.md
  src/styles/page-template/index.md
  stylelint.config.js
  views/partials/_example.njk
Labels: assurance

#3044 Links to meet WCAG 2.1
  src/styles/typography/index.md
Labels: accessibility, guidance

#1668 Add example of summary list with missing information
  src/components/summary-list/index.md
  src/components/summary-list/with-missing-information/index.njk
Labels: submitted by user, summary list, guidance

#3049 Configure Nunjucks from `lib/nunjucks`, consolidate slugs
  lib/get-macro-options/index.js
  lib/metalsmith.js
  lib/nunjucks/filters.js
  lib/nunjucks/filters.test.mjs
  lib/nunjucks/globals.js
  lib/nunjucks/index.js
  package-lock.json
  package.json
  views/partials/_example.njk
Labels: tooling, interoperability

#3105 Update to addresses pattern to include more error examples
  src/patterns/addresses/error-messages/address-wrapper.scss
  src/patterns/addresses/error-messages/index.njk
  src/patterns/addresses/error-postcode/index.njk
  src/patterns/addresses/index.md
Labels: accessibility, error message, guidance

#3002 Apply “smart” punctuation to macro options, titles, meta tags
  lib/get-macro-options/index.js
  lib/nunjucks/filters.js
  package-lock.json
  package.json
  src/components/accordion/default/index.njk
  src/components/breadcrumbs/collapse-mobile/index.njk
  src/components/error-summary/full-page-example/index.njk
  src/components/error-summary/linking-multiple-fields/index.njk
  src/components/error-summary/linking/index.njk
  src/components/fieldset/address-group/index.njk
  src/components/notification-banner/success/index.njk
  src/components/notification-banner/whole-service/index.njk
  src/components/summary-list/without-borders/index.njk
  src/components/table/column-widths-custom-classes/index.njk
  src/components/table/column-widths/index.njk
  src/cookies.njk
  src/patterns/addresses/multiple/index.njk
  src/patterns/check-answers/default/index.njk
  src/patterns/contact-a-department-or-service-team/expanding-contact-information/index.njk
  src/styles/page-template/custom/code.njk
  src/styles/page-template/custom/index.njk
  views/layouts/_generic.njk
  views/layouts/layout-example.njk
  views/partials/_banner.njk
  views/partials/_example.njk
Labels: typography, tooling, website

#3107 Fix duplicate macro options table captions and IDs
  lib/get-macro-options/index.js
  src/components/footer/index.md
  views/partials/_example.njk
Labels: 🐛 bug

#3108 Update get-in-touch.njk
  src/get-in-touch.njk
Labels: guidance, design system day
