Repository alphagov/govuk-design-system, pull requests merged in 2023-03, with the labels that each got.

#2647 Fix for flaky Windows tests preventing deployment
  .github/workflows/test.yaml
  jest-puppeteer.config.js
  package.json
  tasks/serve.js
  tasks/start.js
  tasks/test-serve.js
Labels: assurance

#2641 Ensure we use `*.mjs` extensions for ES modules
  .babelrc.json
  .browserslistrc
  __tests__/cookie-functions.test.mjs
  babel.config.js
  deploy/nginx/mime.types
  jest.config.mjs
  lib/fingerprints/index.js
  lib/metalsmith.js
  lib/rollup/fixtures/src/javascripts/entry.mjs
  lib/rollup/fixtures/src/javascripts/example.mjs
  lib/rollup/index.js
  lib/rollup/index.test.js
  package-lock.json
  package.json
  src/javascripts/application-ie8.mjs
  src/javascripts/application.mjs
  src/javascripts/components/analytics.mjs
  src/javascripts/components/back-to-top.mjs
  src/javascripts/components/cookie-banner.mjs
  src/javascripts/components/cookie-functions.mjs
  src/javascripts/components/cookies-page.mjs
  src/javascripts/components/copy.mjs
  src/javascripts/components/example.mjs
  src/javascripts/components/helpers.mjs
  src/javascripts/components/navigation.mjs
  src/javascripts/components/options-table.mjs
  src/javascripts/components/search.mjs
  src/javascripts/components/search.tracking.mjs
  src/javascripts/components/tabs.mjs
  src/javascripts/example.mjs
  src/javascripts/govuk-frontend.mjs
  src/javascripts/head-ie8.mjs
Labels: dependencies, consistency

#2642 Remove IE8-10 scripts, styles, comments, polyfills etc
  .browserslistrc
  .github/dependabot.yml
  .htmlvalidate.js
  config/modernizr.json
  lib/metalsmith.js
  lib/modernizr-build.js
  lib/rollup/index.js
  package-lock.json
  package.json
  package.json.unit.test.js
  src/cookies.njk
  src/javascripts/application-ie8.mjs
  src/javascripts/components/back-to-top.mjs
  src/javascripts/components/cookie-banner.mjs
  src/javascripts/components/copy.mjs
  src/javascripts/components/helpers.mjs
  src/javascripts/components/navigation.mjs
  src/javascripts/components/options-table.mjs
  src/javascripts/components/search.mjs
  src/javascripts/components/tabs.mjs
  src/javascripts/example.mjs
  src/javascripts/head-ie8.mjs
  src/styles/page-template/block-areas/index.njk
  src/styles/page-template/custom/code.njk
  src/styles/page-template/custom/index.njk
  src/styles/page-template/default/code.njk
  src/styles/page-template/default/index.njk
  src/stylesheets/components/_cookies-page.scss
  src/stylesheets/components/_masthead.scss
  src/stylesheets/components/_navigation.scss
  src/stylesheets/components/_site-search.scss
  src/stylesheets/components/_split-pane.scss
  src/stylesheets/components/_tabs.scss
  src/stylesheets/main-ie8.scss
  src/stylesheets/main.scss
  views/layouts/_generic.njk
  views/layouts/layout-example-full-page-govuk.njk
  views/layouts/layout-example-full-page.njk
  views/layouts/layout-example.njk
  views/partials/_example.njk
  views/partials/_header.njk
Labels: dependencies, consistency

#2684 Make it clearer who the design system is aimed at
  src/index.njk
  src/styles/index.md
  views/partials/_masthead.njk
Labels: website

#2672 Add guidance on how tab values get stored in URL
  src/components/tabs/index.md
Labels: tabs

#2704 Fix argument count in deprecated `this.mql.addListener()`
  src/javascripts/components/navigation.mjs
Labels: 🐛 bug
