Repository alphagov/govuk-design-system, pull requests merged in 2023-09, with the labels that each got.

#3114 Remove parent prefix from nested component display names
  lib/get-macro-options/index.js
Labels: documentation, website

#3116 Various fixes for `html-validate` (cookie banner buttons)
  __tests__/cookies-page.test.js
  src/components/cookie-banner/client-side-accepted/index.njk
  src/components/cookie-banner/client-side-rejected/index.njk
  src/components/cookie-banner/client-side/index.njk
  src/components/cookie-banner/default/index.njk
  src/components/cookie-banner/multiple-cookies/index.njk
  src/components/cookie-banner/server-side-confirmation/index.njk
  src/components/cookie-banner/server-side-multiple-messages-confirmation-visible/index.njk
  src/components/cookie-banner/server-side-multiple-messages-question-visible/index.njk
  src/components/cookie-banner/server-side/index.njk
  src/cookies.njk
  src/javascripts/components/cookies-page.mjs
  src/patterns/cookies-page/cookies-form/index.njk
  src/styles/page-template/custom/code.njk
  src/styles/page-template/custom/index.njk
  views/partials/_cookie-banner.njk
Labels: 🐛 bug, assurance, cookie banner

#2928 Show nested option type in table captions
  lib/get-macro-options/index.js
  src/stylesheets/main.scss
Labels: documentation, design, website

#3179 Use summary list for key facts, heading semantics etc
  docs/contributing/adding-images-to-the-wesite.md
  src/code-of-conduct.md
  src/community/call-for-speakers-2023/index.md
  src/community/design-system-day/index.md
Labels: accessibility, website

#3178 Add a link to GOV.UK Frontend ASP.NET Core library
  src/community/resources-and-tools/index.md
Labels: submitted by user, documentation

#3180 Fix local `search-index.json` test (no hash fingerprint)
  __tests__/search.test.js
Labels: 🐛 bug, assurance
