Repository alphagov/govuk-design-system, pull requests merged in 2023-04, with the labels that each got.

#2740 Update to `govuk-frontend@4.6.0`
  package-lock.json
  package.json
Labels: dependencies

#2742 Include sources content from `govuk-frontend` source maps
  rollup.config.js
Labels: 🐛 bug

#2694 Add guidance about optional questions
  src/patterns/check-answers/index.md
Labels: check answers

#2695 Add example for showing a field that was optional
  src/patterns/check-answers/default/index.njk
Labels: check answers

#2696 Add 'card actions' bolding explanation to summary card content
  src/components/summary-list/index.md
Labels: accessibility, guidance, support
