Repository alphagov/govuk-design-system, pull requests merged in 2024-01, with the labels that each got.

#3406 Add links to GitHub discussions on links and lists pages
  src/styles/links/index.md
  src/styles/lists/index.md
Labels: small story

#3425 Fix navigation `$from: tablet` gutter offset
  src/stylesheets/components/_navigation.scss
Labels: design, navigation

#3418 Add Mural template to 'Create prototypes and wireframes'
  src/community/resources-and-tools/index.md
Labels: design

#3458 Add 'what' into WCAG 2.2 page
  src/accessibility/wcag-2.2/index.md
Labels: guidance
