Repository alphagov/govuk-design-system, pull requests merged in 2025-02, with the labels that each got.

#4486 Remove old usage survey link
  views/partials/_contact-panel.njk
Labels: documentation, research

#4491 Fix deployment links in README.md
  README.md
Labels: documentation

#4500 Adjust dependabot frequency
  .github/dependabot.yml
Labels: dependencies, tooling
